version: "3"
services:
  client:
    build: .
    image: ops/client:latest
    ports:
      - "8000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/client/healthcheck"]
    environment:
      - FLASK_ENV=development
      - APP_ENV=
      - SERVICE_NAME=client
      - ALB=localhost:8001      -
  crud:
    image: ops/crud:latest
    ports:
      - "8001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/crud/healthcheck"]
    environment:
      - FLASK_ENV=development
      - APP_ENV=
      - SERVICE_NAME=crud
