version: "3"
services:
  client:
    build: .
    image: ops/client:latest
    ports:
      - "8000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/client/admin/healthcheck"]
    environment:
      - FLASK_ENV=development
      - SERVICE_NAME=client
      - SERVICE_VERSION=1.2.3
      - ALB=crud:5000
  crud:
    image: ops/crud:latest
    ports:
      - "8001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/crud/admin/healthcheck"]
    environment:
      - FLASK_ENV=development
      - SERVICE_NAME=crud
      - SERVICE_VERSION=1.2.3
